export const projects = [


  {
    title: 'MollyBarnesMusic.com',
    description: "A freelance website for Dr. Molly Barnes, meant to showcase and promote her work as a professor of Musicology, live performer, and advertise private music lessons through the Skylark Music School.  This application utilizes Next.js, CSS Modules, as well as JavaScript logic for pagination, dropdown menus, and random quote retrieval.",
    image: '/images/molly_laptop_1.png',
    tags: ['Next.js', 'CSS Modules', 'HTML', 'JavaScript'],
    source: 'https://www.mollybarnesmusic.com/',
    visit: 'https://github.com/jlayher/molly-barnes-music',
    id: 0,
  },
  {
    title: 'SushiMan',
    description: "SushiMan is a dynamic, animated, and visually stunning webite for a fictional Japanese restaurant.  AOS (Animate on Scroll), and various CSS styling tricks, make an otherwise simple website feel engaging and lively as users scroll through, and interact with the web page.",
    image: '/images/SushiMan1.png',
    tags: ['HTML', 'CSS', 'AOS', 'Node.js'],
    source: 'https://sushiman-orpin.vercel.app/',
    visit: 'https://github.com/jlayher/Sushi',
    id: 1,
  },
  {
    title: 'Coin Flip Betting Game',
    description: "This React based application allows users to place monetary bets on the outcome of a coin toss!  Utilizing React Hooks and state management, this application automatically updates and displays current game data, and provides users a complete history of the bets and outcomes throughout their play session.",
    image: '/images/coin_flip_vite_1.png',
    tags: ['React', 'JavaScript', 'CSS', 'HTML'],
    source: 'https://coin-flip-vite.vercel.app/',
    visit: 'https://github.com/jlayher/Coin_Flip_Vite/tree/master',
    id: 2,
  },
  {
    title: 'School Database: Full-Stack React & REST API',
    description: "This is a Full-Stack web application modeling a school’s database.  The application allows for users to Sign-In and Sign-Up.  Authenticated users are able to perform a number of basic CRUD operations, allowing them to Get, Create, Update, and Delete certain “Courses” from the database that they are authorized for.",
    image: '/images/0.png',
    tags: ['React', 'Express', 'SQL(SQLite)', 'Node.js'],
    source: 'N/A',
    visit: 'https://github.com/jlayher/FS-React-REST-API',
    id: 3,
  },
  {
    title: 'What is GPT-3',
    description: "'What is GPT-3' is a responsive Front-End UI for a fictional technology company, promoting GPT-3.  This project uses all of the fundamentals of modern React.js sites, including React Hooks, eye-catching CSS styles, as well as an intuitive, and captivating page layout.",
    image: '/images/1.png',
    tags: ['React', 'Figma', 'CSS', 'JSX', 'JavaScript'],
    source: 'https://jlayher.github.io/React-GPT3-FE/',
    visit: 'https://github.com/jlayher/React-GPT3-FE/tree/master',
    id: 4,
  },
  {
    title: 'Employee Directory: AJAX Application',
    description: "This application uses AJAX to communicate with the Random User Generator API to fetch data and display a list of 12 random “employees” from a fictional start-up company.  Users can dynamically search for employees, click on an employee’s card to reveal more information in a modal window, and navigate between employees within the modal window.",
    image: '/images/2.png',
    tags: ['JavaScript', 'Fetch API', 'HTML', 'CSS'],
    source: 'https://jlayher.github.io/Employee-Directory-AJAX-App/',
    visit: 'https://github.com/jlayher/Employee-Directory-AJAX-App',
    id: 5,
  },
  {
    title: 'React Image Gallery with Flickr API',
    description: "This web application uses React.js to create an image gallery, utilizing Axios to fetch data from the Flickr API.  The application allows for users to search for various image topics in the Flickr database, or select from several present image search options, and will render images of the user’s search in an image grid.",
    image: '/images/3.png',
    tags: ['React', 'React Router', 'JavaScript', 'Axios'],
    source: 'N/A',
    visit: 'https://github.com/jlayher/React-Gallery-App',
    id: 6,
  },
  {
    title: 'Library Database CRUD Application',
    description: "A fictional library database that utilizes a SQLite database, Express.js back-end, Sequelize (ORM), and Pug templating.  Allows users to perform basic CRUD operations using a simple front-end interface.",
    image: '/images/4.png',
    tags: ['JavaScript', 'Node.js', 'Express', 'SQL', 'Pug'],
    source: 'N/A',
    visit: 'https://github.com/jlayher/Library-DB-Express',
    id: 7,
  },
  {
    title: 'Phrase Hunter: Object Oriented Programming Game',
    description: "A browser-based, word guessing game using JavaScript and Object-Oriented Programming.  The program selects, and hides a random phrase, which the player must guess using a keyboard, or the onscreen keyboard.",
    image: '/images/5.png',
    tags: ['JavaScript', 'CSS', 'HTML'],
    source: 'https://jlayher.github.io/Object-Oriented-Programming-Game/',
    visit: 'https://github.com/jlayher/Object-Oriented-Programming-Game',
    id: 8,
  },
  {
    title: 'Angular Tic-Tac-Toe',
    description: "A simple Tic-Tac-Toe application, utilizing Angular, TypeScript, SCSS, HTML, and the Angular UI Library Nebular.  The application tracks the current user, provides animations and styles on button click, and alerts the user when, and which player has won the game.",
    image: '/images/7.png',
    tags: ['Angular', 'TypeScript', 'HTML', 'SCSS', 'Nebular'],
    source: 'N/A',
    visit: 'https://github.com/jlayher/angular_tic_tac_toe',
    id: 9,
  },

];


export const TimeLineData = [
  { year: "May 2019", text: "Graduated from Elon University"},
  { year: "May 2021", text: 'Received Full-Stack JavaScript Techdegree from Treehouse'},
  { year: "September 2021", text: "Joined Infosys: Worked on Toyota's Advanced Cloud Engineering project"},
  { year: "March 2022", text: "Performed UI/UX for Toyota's Smartpath and Lexus's Monogram web applications"},
  { year: "December 2022", text: 'Began Freelancing Web-Design' },
];